'use client';

import { createClient } from '@/lib/supabase/client';
import type { AttemptRow, ClassRow, ProfileRow } from './types';

export type StudentBrief = Pick<ProfileRow, 'id' | 'full_name' | 'email' | 'avatar_url' | 'class_id'>;

/** An attempt joined with its student, for the teacher dashboard. */
export interface AttemptWithStudent extends AttemptRow {
  student: StudentBrief;
}

export interface AssignmentRow {
  id: string;
  class_id: string;
  tp_id: string;
  due_at: string | null;
  created_at: string;
}

/** Creates a class; the join code is generated by the database default. */
export async function createClass(name: string, level?: string): Promise<ClassRow> {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Session expirée : reconnecte-toi.');
  const { data, error } = await supabase
    .from('classes')
    .insert({ name, level: level ?? null, teacher_id: user.id })
    .select('id, name, level, teacher_id, join_code')
    .single();
  if (error) throw new Error(error.message);
  return data as ClassRow;
}

export async function listMyClasses(): Promise<ClassRow[]> {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return [];
  const { data, error } = await supabase
    .from('classes')
    .select('id, name, level, teacher_id, join_code')
    .eq('teacher_id', user.id)
    .order('name');
  if (error) throw new Error(error.message);
  return (data ?? []) as ClassRow[];
}

export async function listClassStudents(classId: string): Promise<StudentBrief[]> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('profiles')
    .select('id, full_name, email, avatar_url, class_id')
    .eq('class_id', classId)
    .order('full_name');
  if (error) throw new Error(error.message);
  return (data ?? []) as StudentBrief[];
}

/** Every attempt of the students of one class, newest first. */
export async function listClassAttempts(classId: string): Promise<AttemptWithStudent[]> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('attempts')
    .select('*, student:profiles!inner(id, full_name, email, avatar_url, class_id)')
    .eq('student.class_id', classId)
    .order('updated_at', { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as unknown as AttemptWithStudent[];
}

export async function assignTp(classId: string, tpId: string, dueAt?: string | null): Promise<AssignmentRow> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('assignments')
    .insert({ class_id: classId, tp_id: tpId, due_at: dueAt ?? null })
    .select('*')
    .single();
  if (error) throw new Error(error.message);
  return data as AssignmentRow;
}

export async function listAssignments(classId: string): Promise<AssignmentRow[]> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('assignments')
    .select('*')
    .eq('class_id', classId)
    .order('created_at', { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as AssignmentRow[];
}

/** Measurements + chat of one attempt (teacher detail view, RLS-checked). */
export async function getAttemptDetail(attemptId: string) {
  const supabase = createClient();
  const [measurements, messages] = await Promise.all([
    supabase.from('measurements').select('*').eq('attempt_id', attemptId).order('created_at'),
    supabase.from('messages').select('*').eq('attempt_id', attemptId).order('created_at'),
  ]);
  if (measurements.error) throw new Error(measurements.error.message);
  if (messages.error) throw new Error(messages.error.message);
  return {
    measurements: (measurements.data ?? []) as {
      id: string; stage: number; instrument: string; point: string;
      value: number | null; display: string | null; created_at: string;
    }[],
    messages: (messages.data ?? []) as {
      id: string; stage: number; role: 'user' | 'assistant'; content: string; created_at: string;
    }[],
  };
}
